### ISSUE TITLE
request of 'off' method

### ISSUE THREAD

**Issue by y-ich** [wojtkowiak/meteor-custom-protocol#1]
Hi.

 Since I add and remove chat session dynamically, I needed 'off' method.
Here is a snippet that I added. (CoffeeScript)

    DynamicMessagesProtocol::off = (messageType, callback) ->
        unless @_callback[messageType]?
            return
        
        if callback?
            index = @_callback[messageType].indexOf callback
            @_callback[messageType].splice index, 1
        else
            delete @_callback[messageType]
        return

If you add these methods in your package, I will appreciate it.

**Comment by wojtkowiak** [comment]
Hello,

that is a reasonable request. I will add it today.

**Comment by wojtkowiak** [comment]
Added through https://github.com/wojtkowiak/meteor-custom-protocol/commit/92d4ac9cce670dd309e302a1d6ba5aedcafb1892

**Comment by y-ich** [comment]
It seems to work well.
Thank you!
