### ISSUE TITLE
Message handling on different clients.

### ISSUE THREAD

**Issue by Dranithix** [wojtkowiak/meteor-custom-protocol#2]
First off,

Thanks so much for the package and really hope it continues to grow as there's so many uses for this :). I wanted to ask if you could clarify on how `JsonProtocol` determines what is a received JSON document apart from the entire DDP protocol.

I'm looking into making an Android client for my Meteor website so that I could receive selected data, and it'd get messy if I accidentally handle a DDP message instead of my own protocol instead.

Thanks,

**Comment by wojtkowiak** [comment]
Sorry for late answer, I was on holidays :smile:

Any message sent with custom protocols starts with a 16bit header:
https://github.com/wojtkowiak/meteor-custom-protocol/blob/master/src/lib/core.js#L134

Normal DPP message starts with `{` as it is a stringified JSON, which in bits looks like `0111 1011`.

You can just check for first bit in first char in the message. If it is 0 then it is a custom protocol message.
The body of the message (in case of `JsonProtocol` it is also a stringified JSON) starts at char index 2 in the message string (as first two chars are used by the header).

**Comment by Dranithix** [comment]
Helped out a bunch, thanks a lot :+1: .
