### ISSUE TITLE
A very nice tool, a couple of questions

### ISSUE THREAD

**Issue by theodorDiaconu** [wojtkowiak/meteor-custom-protocol#3]
```
// sessionId is only provided on server
protocol.on('myMessage', (data, sessionId) => {});
```
Can we get the userId in here ?

Basically what I need is this:
https://github.com/cult-of-coders/redis-oplog/issues/179

I need to emit events, but I want a unidirectional communication. Server->Client. I'd prefer the client to send-out changes through Meteor's RPC, to have full control over it.

Any tips before I dive into digesting this nice package ?

**Comment by theodorDiaconu** [comment]
Also @wojtkowiak , how do I create that protocol file inside a package, where I don't have access to Meteor's private assets ?

**Comment by wojtkowiak** [comment]
> Can we get the userId in here ?

Yes, I can add support for it.

> Also @wojtkowiak , how do I create that protocol file inside a package, where I don't have access to ?
> Meteor's private assets ?

This is supported. Here I have a protocol in a package. 
https://github.com/wojtkowiak/meteor-transfer-rate-monitor/tree/master/src/lib
You just need to
```
api.use('omega:custom-protocol@3.1.0', ['client', 'server']);
api.imply('omega:custom-protocol', ['client', 'server']);
```

Also this package itself has the JsonProtocol here:
https://github.com/wojtkowiak/meteor-custom-protocol/tree/master/src/utils


Well I admit that I had to overcome several limitations with meteor build system while developing this and I had to accept solutions that I am not very comfortable with. One of that are the empty files you need to create along with the protocol code and the fact that the index is generated and stored in assets.

**Comment by theodorDiaconu** [comment]
@wojtkowiak 
```
Meteor.publish('subscribeToMyProtocol', function () {
    let sessionId = this.connection.id;
       
    // Here store the sessionId somewhere.
    // You can also store this.userId of subscribed client and therefore be able to send to specified clients based on the user ids.
     
    this.onStop(() => {
        // Here delete the stored sessionId.
    });
});
```

I don't really understand how to use this, can you elaborate on your example ?

**Comment by wojtkowiak** [comment]
Sorry for the delay... hectic week.
So basically you need to know the session ids of clients you want to send to. (session id is the connection id assigned internally by Meteor)
With this dummy publication (assuming that a client would always subscribe) you can create a in memory list of `userId -> [sessionId, sessionId]` pairs (remember that one user can have many session ids in case he is connected multiple times).

If you would like to broadcast something to all connected clients without exceptions you can maintain a list of all sessions id with this dummy publication or get a list o session ids by iterating over `Meteor.server.sessions`

**Comment by wojtkowiak** [comment]
Hmm actually direct-stream-access has a [broadcast](https://github.com/wojtkowiak/meteor-direct-stream-access/blob/master/SERVER.md#DirectStreamAccess+broadcast) method so if you want I can make custom-protocols inherit that.

**Comment by theodorDiaconu** [comment]
@wojtkowiak thanks for your response. I looked at the code of this, and as much as I like it I realized that for my needs it's better to use DDP Transport, I found a way to bypass mergebox. However, I see potential in using this in other scenarios.
