### ISSUE TITLE
Error: Protocol MyProtocol did not receive unique id. Check if the file name is in format `<name>.protocol.js` so that the indexer can assign an id to it

### ISSUE THREAD

**Issue by Fabbok1x** [wojtkowiak/meteor-custom-protocol#6]
Hello,
when using this package with Meteor React the this error will occur during build:
`Error: Protocol MyProtocol did not receive unique id. Check if the file name is in format `<name>.protocol.js` so that the indexer can assign an id to it`

Originating from /lib/common.js Line 50:
```
        if (!CustomProtocolsIndex[name]) {
            throw new Error(`Protocol ${name} did not receive unique id. Check if the file name is `
                + 'in format `<name>.protocol.js` so that the indexer can assign an id to it.');
        }
```

The folder private exists in the root of the dir, with the file custom_protocols_index.json:
```

{
    "JsonProtocol": {
        "id": 1,
        "package": "omega:custom-protocol"
    },
    "MyProtocol": {
        "id": 2,
        "package": "app"
    }
}
```

The protocol exists in /imports/ui , 

My.protocol.js
```
class MyProtocol extends CustomProtocol {
    constructor() {
        super();
        this.MY_MESSAGE = 1;
        this._messages[this.MY_MESSAGE] = { /*definition object*/ };
        this.registerProtocol('MyProtocol'); // pass your class name
     }
    encode(messageId, definition, ...payload) {
        return JSON.stringify(payload[0]);
    }

    decode(messageId, definiton, rawMessage) {
        return JSON.parse(rawMessage);
    }
}


export default  new MyProtocol();
```

My.protocol
[Empty]

Is there a fix or workarround for this issue?

**Comment by wojtkowiak** [comment]
Hey,

at a first glance it looks totally fine. Could you make a simple small repro for this?

**Comment by Fabbok1x** [comment]
Hey there,
sorry was mistaken. Thought the communication was supposed to work between client <-> server.

Neverminded. Thanks anyways.

**Comment by wojtkowiak** [comment]
Ok... it works that way, I mean you can freely send messages in both directions. Let me know if you need any further assistance.

**Comment by Fabbok1x** [comment]
Oh, You mean, it's supposed to work from Server to Client and Client to Server?

**Comment by wojtkowiak** [comment]
Yes, this is bi-directional. You can send anything from client to server and vice versa anytime you want.
