### ISSUE TITLE
Multi-Server Support?

### ISSUE THREAD

**Issue by evolross** [wojtkowiak/meteor-custom-protocol#8]
Is there anyway to support multiple containers and/or micro-services architecture here?  For example, having one admin-app server send messages to three other client-app servers?

`redis-oplog` handles this well by using Redis and completely independent channels.  Was curious if I could implement my setup using this package.

**Comment by wojtkowiak** [comment]
This is not supported. You have to implement your own communication between meteor servers and call the clients directly from the server they are connected to. This however does not seem to be a lot of work.
